const categories = [
  {id:'brakes',label:'Brakes',icon:'◉',group:'Braking systems',title:'Front Brake Kit',count:17,price:184,unit:'/pair',scan:'FRONT AXLE',summary:'',subs:['High performance stopping power','OE fitment and quality','Direct bolt-on installation'],overlay:'<ellipse cx="210" cy="417" rx="48" ry="58" transform="rotate(-8 210 417)"/><ellipse cx="210" cy="417" rx="15" ry="18" transform="rotate(-8 210 417)"/><path d="M236 371q39 29 12 82"/>'},
  {id:'suspension',label:'Suspension',icon:'⌁',group:'Ride & handling',title:'Front Suspension',count:12,price:68,scan:'FRONT SUSPENSION',summary:'OE-standard control and damping parts engineered to restore a composed, quiet ride.',subs:['Shock Absorbers','Control Arms','Bushings','Ball Joints'],overlay:'<path d="M205 265v-58m0 12 22 12-22 12 22 12-22 12m13 4 26 44m-39-44-25 44"/>'},
  {id:'engine',label:'Engine',icon:'⌬',group:'Engine systems',title:'Engine Components',count:31,price:26,scan:'2.5L POWERTRAIN',summary:'Service and repair essentials verified against your engine family and production year.',subs:['Filters','Belts','Mounts','Gaskets','Sensors'],overlay:'<path d="M266 177h120l29 25v60H272l-25-32v-34h19Zm35 0v-22h46v22m-51 35h72m-36-35v85"/>'},
  {id:'exhaust',label:'Exhaust',icon:'≈',group:'Exhaust systems',title:'Exhaust & Emissions',count:9,price:54,scan:'UNDERBODY SYSTEM',summary:'Exact-route exhaust and emissions components for confident fit and dependable sealing.',subs:['Mufflers','Catalytic Converters','Sensors','Gaskets'],overlay:'<path d="M330 292c70-13 138-3 191 8 44 9 79 4 116-14m-307 20c70-13 138-3 191 8 44 9 79 4 116-14"/>'},
  {id:'mirrors',label:'Side Mirrors',icon:'◁',group:'Body & visibility',title:'Side Mirrors',count:8,price:75,scan:'DRIVER MIRROR',summary:'Vehicle-specific mirror assemblies with the correct connector, heating and adjustment options.',subs:['Mirror Glass','Assemblies','Indicators','Covers'],overlay:'<path d="M385 159q-33-32-63-8l10 26q34 8 53-18Z"/>'},
  {id:'headlights',label:'Headlights',icon:'◒',group:'Lighting systems',title:'Headlights',count:14,price:96,scan:'FRONT LIGHTING',summary:'Road-legal lighting matched to your body generation, beam type and connector layout.',subs:['Headlamp Units','LED Modules','Bulbs','Level Sensors'],overlay:'<path d="M101 227q33-23 75-17l31 21q-54 23-106 11Z"/>'},
  {id:'wheels',label:'Wheels',icon:'⊚',group:'Wheels & hubs',title:'Wheels & Hubs',count:23,price:39,scan:'WHEEL ASSEMBLY',summary:'Hub, bearing and wheel components sized to your vehicle’s original specifications.',subs:['Wheel Bearings','Hubs','Bolts','Rims'],overlay:'<circle cx="674" cy="317" r="58"/><circle cx="674" cy="317" r="25"/><path d="m674 292 14 19 23-7-9 23 15 18-25-1-13 21-7-24-24-7 20-14-1-25 20 15Z"/>'},
  {id:'taillights',label:'Tail Lights',icon:'◐',group:'Lighting systems',title:'Tail Lights',count:0,price:null,scan:'REAR LIGHTING',summary:'Rear lighting assemblies matched to the correct body shape, market and connector type.',subs:['Tail Lamps','LED Modules','Bulb Holders'],overlay:'<path d="M760 185q52 3 69 25l-3 24-54-8Z"/>'}
];
categories.push(
  {id:'windshield',label:'Windshield',icon:'▱',group:'Glass & visibility',title:'Front Windshield',count:6,price:215,scan:'FRONT GLASS',summary:'Exact-shape laminated glass matched to your body generation and sensor package.',subs:['Laminated safety glass','Correct sensor bracket','Exact perimeter fit']},
  {id:'wipers',label:'Wipers',icon:'⌒',group:'Glass & visibility',title:'Windshield Wipers',count:19,price:18,scan:'WIPER SYSTEM',summary:'Quiet, streak-free blades and service components sized for the Camry XV70.',subs:['Driver and passenger sizes','All-weather compounds','OE-style connectors']},
  {id:'brake-pads',label:'Brake Pads',icon:'▰',group:'Braking systems',title:'Front Brake Pads',count:24,price:42,scan:'FRONT PADS',summary:'Low-dust friction compounds matched to the correct caliper and rotor dimensions.',subs:['Axle-set packaging','Wear-sensor compatible','OE friction specification']},
  {id:'brake-rotors',label:'Brake Rotors',icon:'◉',group:'Braking systems',title:'Front Brake Rotors',count:17,price:89,unit:'/each',scan:'FRONT ROTORS',summary:'Vehicle-specific coated rotors with precise hub, diameter and thickness dimensions.',subs:['Correct rotor diameter','Balanced and coated','Direct-fit hub pattern']},
  {id:'fog-lights',label:'Fog Lights',icon:'◖',group:'Lighting systems',title:'Fog Light Assemblies',count:8,price:64,scan:'LOWER LIGHTING',summary:'Direct-fit lower bumper lighting with the correct brackets and connectors.',subs:['Road-legal beam pattern','Plug-in connector','Exact bumper mounting']},
  {id:'battery',label:'Battery',icon:'▣',group:'Electrical systems',title:'12V Starter Battery',count:11,price:118,scan:'ELECTRICAL SUPPLY',summary:'Correct-case batteries selected for capacity, terminal orientation and climate performance.',subs:['Correct group size','Heat-resistant design','Starting-power verified']},
  {id:'radiator',label:'Radiator',icon:'▥',group:'Cooling systems',title:'Engine Radiator',count:7,price:149,scan:'FRONT COOLING',summary:'Exact-fit cooling cores matched to transmission type and hose connections.',subs:['Pressure-tested core','Correct hose ports','Transmission cooler ready']},
  {id:'air-filter',label:'Air Filter',icon:'▤',group:'Engine service',title:'Engine Air Filter',count:32,price:16,scan:'AIR INTAKE',summary:'High-efficiency filter media shaped precisely for the original airbox.',subs:['Dust-load optimized','Exact airbox seal','OE airflow specification']},
  {id:'spark-plugs',label:'Spark Plugs',icon:'♢',group:'Ignition systems',title:'Spark Plug Set',count:26,price:38,unit:'/set',scan:'IGNITION SYSTEM',summary:'Correct heat-range plugs matched to the 2.5L engine and service interval.',subs:['Correct heat range','Pre-set electrode gap','Four-plug engine set']},
  {id:'ac-compressor',label:'AC Compressor',icon:'❉',group:'Climate systems',title:'AC Compressor',count:5,price:289,scan:'AIR CONDITIONING',summary:'Vehicle-specific compressors matched to refrigerant type, pulley and hose fittings.',subs:['Correct refrigerant spec','Direct hose connection','Pulley alignment verified']},
  {id:'water-pump',label:'Water Pump',icon:'◌',group:'Cooling systems',title:'Engine Water Pump',count:9,price:82,scan:'COOLANT CIRCUIT',summary:'Precision cooling pumps supplied with the correct seal and mounting pattern.',subs:['Leak-tested assembly','Correct impeller design','Gasket included']},
  {id:'alternator',label:'Alternator',icon:'◍',group:'Electrical systems',title:'Alternator Assembly',count:6,price:198,scan:'CHARGING SYSTEM',summary:'Output-matched charging units with the correct mounts, pulley and connector.',subs:['Factory-rated output','Correct pulley profile','Direct electrical fit']},
  {id:'control-arms',label:'Control Arms',icon:'⌁',group:'Ride & handling',title:'Front Control Arms',count:10,price:76,scan:'FRONT SUSPENSION',summary:'Geometry-correct arms supplied with installed bushings for dependable alignment.',subs:['Bushings installed','Correct suspension geometry','Left and right options']},
  {id:'ball-joints',label:'Ball Joints',icon:'●',group:'Ride & handling',title:'Front Ball Joints',count:14,price:34,scan:'STEERING JOINT',summary:'Load-rated joints matched to the original control arm and steering knuckle.',subs:['Sealed joint design','Correct taper and stud','Mounting hardware included']},
  {id:'wheel-bearings',label:'Wheel Bearings',icon:'⊙',group:'Wheels & hubs',title:'Front Wheel Bearings',count:13,price:58,scan:'WHEEL HUB',summary:'Low-friction bearing and hub units matched to ABS and axle specifications.',subs:['ABS-compatible encoder','Pre-set bearing clearance','Direct-fit hub pattern']},
  {id:'timing-belt',label:'Timing Belt',icon:'∞',group:'Engine service',title:'Timing Belt Service Kit',count:8,price:124,scan:'ENGINE TIMING',summary:'Matched belt and tensioner components for dependable synchronized engine timing.',subs:['Reinforced belt compound','Tensioner included','Service-interval matched']}
);
categories.push(
  {id:'rearview-mirror',label:'Rear-view Mirror',icon:'▭',group:'Interior & visibility',title:'Interior Rear-view Mirrors',count:7,price:46,scan:'CABIN MIRROR',summary:'Cabin mirrors matched to the original windshield mount and available electronic features.',subs:['Correct windshield mount','Manual and auto-dimming options','Factory-style housing']},
  {id:'door-handles',label:'Door Handles',icon:'━',group:'Body hardware',title:'Exterior Door Handles',count:16,price:29,scan:'DOOR HARDWARE',summary:'Direct-fit exterior handles matched to door position, finish and keyless-entry equipment.',subs:['Front and rear positions','Paint-ready and finished options','Smart-entry compatible']},
  {id:'tires',label:'Tires',icon:'◯',group:'Tires & road contact',title:'Vehicle-fit Tires',count:38,price:112,unit:'/each',scan:'TIRE FITMENT',summary:'Road tires selected by factory size, load rating and speed rating for the Camry XV70.',subs:['Factory size verified','Load and speed rated','All-season options']},
  {id:'rims',label:'Rims',icon:'✥',group:'Wheels & styling',title:'Alloy Rims',count:21,price:168,unit:'/each',scan:'WHEEL DESIGN',summary:'Vehicle-specific alloy rims with the correct diameter, bolt pattern, offset and hub bore.',subs:['Correct bolt pattern','Factory offset range','Hub-centric fit']},
  {id:'seats',label:'Car Seats',icon:'◩',group:'Interior & comfort',title:'Front Seat Components',count:12,price:245,scan:'CABIN SEATING',summary:'Seat assemblies and service components matched to trim, mounting points and safety equipment.',subs:['Correct floor mounting','Airbag-compatible options','Trim-matched finishes']}
);
const vehicles=[
  {brand:'Toyota',model:'Camry',generation:'XV70',year:2021,engine:'2.5L'},
  {brand:'BMW',model:'330i',generation:'G20',year:2023,engine:'2.0L B48'},
  {brand:'Toyota',model:'Corolla',generation:'E210',year:2022,engine:'1.8L'}
];
const vehicleAssetPacks={
  'Toyota|Camry|XV70':{root:'assets/vehicles/toyota/camry/xv70',states:{brakes:'brakes.png',suspension:'suspension.png',engine:'engine.png',exhaust:'exhaust.png',mirrors:'mirrors.png',headlights:'headlights.png',wheels:'wheels.png',taillights:'taillights.png',windshield:'windshield.png',wipers:'wipers.png','brake-pads':'brake-pads.png','brake-rotors':'brake-rotors.png','fog-lights':'fog-lights.png',battery:'battery.png',radiator:'radiator.png','air-filter':'air-filter.png','spark-plugs':'spark-plugs.png','ac-compressor':'ac-compressor.png','water-pump':'water-pump.png',alternator:'alternator.png','control-arms':'control-arms.png','ball-joints':'ball-joints.png','wheel-bearings':'wheel-bearings.png','timing-belt':'timing-belt.png','rearview-mirror':'rearview-mirror.png','door-handles':'door-handles.png',tires:'tires.png',rims:'rims.png',seats:'seats.png'}},
  'BMW|330i|G20':{root:'assets',states:{brakes:'bmw-g20-brakes.png?v=2',suspension:'bmw-g20-blueprint-base.png?v=2',engine:'bmw-g20-blueprint-base.png?v=2',exhaust:'bmw-g20-blueprint-base.png?v=2',mirrors:'bmw-g20-blueprint-base.png?v=2',headlights:'bmw-g20-blueprint-base.png?v=2',wheels:'bmw-g20-blueprint-base.png?v=2',taillights:'bmw-g20-blueprint-base.png?v=2'}}
};
const selectorData={brandGroups:{'China':['Avatr','BAIC','BYD','Changan','Chery','Deepal','Dongfeng','FAW','Foton','GAC','Geely','GWM','Haval','JAC','Jaecoo','Jetour','Leapmotor','Maxus','MG','Neta','Omoda','Riddara','Sinotruk','Wuling','Xpeng','Zeekr'],'Japan':['Honda','Hino','Isuzu','Mitsubishi','Nissan','Suzuki','Toyota'],'Germany':['BMW','MAN','Mercedes-Benz','Volkswagen'],'United Kingdom':['Jaguar','Land Rover','Range Rover'],'United States':['Ford'],'South Korea':['Hyundai','Kia'],'India':['Ashok Leyland','BharatBenz','Mahindra','Maruti Suzuki','Tata']},models:{Toyota:['Camry','Corolla','RAV4','Highlander'],BMW:['330i','320i','X3','X5']},generations:{Camry:[['XV50','2011–2017'],['XV70','2017–2024'],['XV80','2024–present']],Corolla:[['E170','2013–2019'],['E210','2018–present']],"330i":[['F30','2012–2019'],['G20','2019–present']]},years:[2024,2023,2022,2021,2020],engines:['2.5L','2.0L','1.8L','2.0L B48']};
selectorData.brands=Object.values(selectorData.brandGroups).flat();
let active=0,currentVehicle={...vehicles[0]},selectorStep=0,draft={};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function renderCategories(){ $('#categories').innerHTML=categories.map((c,i)=>`<button class="category ${i===active?'active':''}" role="tab" aria-selected="${i===active}" data-index="${i}"><span class="cat-icon">${c.icon}</span><small>${String(i+1).padStart(2,'0')}</small><b>${c.label}</b></button>`).join(''); $$('.category').forEach(b=>b.onclick=()=>selectCategory(+b.dataset.index)); $('#pagination').innerHTML=categories.map((_,i)=>`<i class="${i===active?'active':''}"></i>`).join('')}
function renderDetail(){const c=categories[active];$('#scanLabel').textContent=c.scan;$('#detailPanel').innerHTML=`<span class="kicker">${c.group}</span><h2>${c.title}</h2><div class="subcats">${c.subs.map(x=>`<span><b>✓</b>${x}</span>`).join('')}</div>${c.summary?`<p class="summary">${c.summary}</p>`:''}<div class="price-row"><div>${c.price?`<div class="from">From</div><div class="price">$${c.price}<small>${c.unit||''}</small></div>`:'<div class="from">Availability updates</div><div class="price" style="font-size:16px">Notify me</div>'}</div><button class="primary" id="viewParts" ${c.count?'':'disabled'}>${c.count?`View ${c.label} parts →`:'Notify me'}</button></div>`; if(c.count)$('#viewParts').onclick=renderInventory}
function getVehicleAsset(categoryId){const key=`${currentVehicle.brand}|${currentVehicle.model}|${currentVehicle.generation}`;const pack=vehicleAssetPacks[key]||vehicleAssetPacks['Toyota|Camry|XV70'];return `${pack.root}/${pack.states[categoryId]||'base.png'}`}
function updateVehicleImage(){const img=$('#vehicleImage');img.classList.add('is-changing');setTimeout(()=>{const c=categories[active];img.src=getVehicleAsset(c.id);img.alt=`${currentVehicle.brand} ${currentVehicle.model} technical illustration with highlighted ${c.label.toLowerCase()}`;img.classList.remove('is-changing')},160)}
function selectCategory(index){active=(index+categories.length)%categories.length;$('#detailPanel').classList.add('changing');updateVehicleImage();setTimeout(()=>{$('#partOverlay').innerHTML='';renderCategories();renderDetail();requestAnimationFrame(()=>$('#detailPanel').classList.remove('changing'));$('.category.active').scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})},180)}
function updateVehicle(){ $('#vehicleName').textContent=`${currentVehicle.brand} ${currentVehicle.model}`;$('#vehicleSpec').textContent=`${currentVehicle.generation} · ${currentVehicle.year} · ${currentVehicle.engine}`;updateVehicleImage() }
$('#prevCategory').onclick=()=>selectCategory(active-1);$('#nextCategory').onclick=()=>selectCategory(active+1);$('#vehicleStage').onkeydown=e=>{if(e.key==='ArrowRight')selectCategory(active+1);if(e.key==='ArrowLeft')selectCategory(active-1)};
let startX=0;$('#vehicleStage').addEventListener('pointerdown',e=>startX=e.clientX);$('#vehicleStage').addEventListener('pointerup',e=>{const d=e.clientX-startX;if(Math.abs(d)>45)selectCategory(active+(d<0?1:-1))});
function showSelector(){selectorStep=0;draft={};renderSelector();$('#vehicleDialog').showModal()}
function renderSelector(){const titles=['Choose your brand','Choose a model','Choose a generation','Choose a year','Choose engine / variant'];$('#selectorTitle').textContent=titles[selectorStep];$('#selectorProgress').innerHTML=titles.map((_,i)=>`<i class="${i<=selectorStep?'done':''}"></i>`).join('');if(selectorStep===0){$('#selectorOptions').innerHTML=`<div class="brand-dropdown"><label for="brandSelect">Vehicle manufacturer</label><select id="brandSelect"><option value="">Select a brand</option>${Object.entries(selectorData.brandGroups).map(([country,brands])=>`<optgroup label="${country}">${brands.map(brand=>`<option value="${brand}">${brand}${selectorData.models[brand]?' — available now':''}</option>`).join('')}</optgroup>`).join('')}</select><button class="primary wide" id="brandContinue" disabled>Continue →</button><p class="brand-status" id="brandStatus">Toyota and BMW are available now. Images for the remaining brands will be added next.</p></div>`;const select=$('#brandSelect'),button=$('#brandContinue');select.onchange=()=>{button.disabled=!select.value||!selectorData.models[select.value];$('#brandStatus').textContent=selectorData.models[select.value]?'Models available — continue to choose your vehicle.':`${select.value} has been added to the brand catalog. Models and vehicle images are coming soon.`};button.onclick=()=>chooseStep(select.value);$('#backStep').classList.add('hidden');return}let opts;if(selectorStep===1)opts=selectorData.models[draft.brand].map(x=>[x,'']);if(selectorStep===2)opts=(selectorData.generations[draft.model]||[['Current generation','2019–2026']]);if(selectorStep===3)opts=selectorData.years.map(x=>[x,'']);if(selectorStep===4)opts=selectorData.engines.map(x=>[x,'']);$('#selectorOptions').innerHTML=opts.map(x=>`<button class="selector-option" data-value="${x[0]}">${x[0]}${x[1]?`<small>${x[1]}</small>`:''}</button>`).join('');$$('.selector-option').forEach(b=>b.onclick=()=>chooseStep(b.dataset.value));$('#backStep').classList.toggle('hidden',selectorStep===0)}
function chooseStep(v){const keys=['brand','model','generation','year','engine'];draft[keys[selectorStep]]=v;if(selectorStep<4){selectorStep++;renderSelector()}else{currentVehicle={...draft,year:+draft.year};if(!vehicles.some(x=>JSON.stringify(x)===JSON.stringify(currentVehicle)))vehicles.push({...currentVehicle});updateVehicle();$('#vehicleDialog').close();renderGarage()}}
$('#changeVehicle').onclick=showSelector;$('#brandsBtn').onclick=showSelector;$('#closeDialog').onclick=()=>$('#vehicleDialog').close();$('#backStep').onclick=()=>{selectorStep--;renderSelector()};
function renderGarage(){ $('#garageList').innerHTML=vehicles.map((v,i)=>`<button class="garage-car ${v.brand===currentVehicle.brand&&v.model===currentVehicle.model?'active':''}" data-car="${i}"><strong>${v.year} ${v.brand} ${v.model}</strong><span>${v.generation} · ${v.engine}</span></button>`).join('');$$('.garage-car').forEach(b=>b.onclick=()=>{currentVehicle={...vehicles[+b.dataset.car]};updateVehicle();$('#garageDialog').close()})}
$('#garageBtn').onclick=()=>{renderGarage();$('#garageDialog').showModal()};$('[data-close-garage]').onclick=()=>$('#garageDialog').close();$('#addGarageVehicle').onclick=()=>{$('#garageDialog').close();showSelector()};
const productNames={brakes:['Front Ceramic Brake Pad Set','Coated Front Brake Rotor','Front Caliper Assembly'],suspension:['Front Control Arm','Gas Pressure Strut','Stabilizer Link'],engine:['Engine Air Filter','Serpentine Belt','Engine Mount'],exhaust:['Oxygen Sensor','Exhaust Gasket','Rear Muffler'],mirrors:['Heated Mirror Glass','Power Mirror Assembly','Mirror Indicator'],headlights:['LED Headlamp Unit','Headlight Module','D4S Xenon Bulb'],wheels:['Front Wheel Hub','Wheel Bearing Kit','Alloy Wheel Bolt']};
function renderInventory(){const c=categories[active],names=productNames[c.id]||[`OE-Spec ${c.title}`,`Premium ${c.label} Replacement`,`Value-Line ${c.label}`];$('#explorerView').classList.add('hidden');$('#inventoryView').classList.remove('hidden');$('#inventoryView').innerHTML=`<div class="inventory-head"><div><button class="back-home">← Vehicle explorer</button><p class="eyebrow">${currentVehicle.brand} ${currentVehicle.model} · ${currentVehicle.generation} · ${currentVehicle.year} · ${currentVehicle.engine}</p><h1>${c.label} parts</h1><p style="color:var(--success)">✓ Showing compatible parts only</p></div><p>${c.count} results</p></div><div class="inventory-body"><aside class="filters"><h3>Filter results</h3>${['Front / Rear','Brand','OEM / Aftermarket','Price','Availability'].map(x=>`<div class="filter">${x}<span style="float:right">＋</span></div>`).join('')}</aside><section class="product-grid">${names.map((n,i)=>`<article class="product-card"><div class="product-image">${c.icon}</div><div class="maker">${['BREMBO','BOSCH','FEBI BILSTEIN'][i]}</div><h3>${n}</h3><div class="sku">${['09.C394.13','NA-2847-OE','FB-7712'][i]}</div><div class="fits">✓ Fits your ${currentVehicle.model}</div><div class="buy-row"><div><strong>$${(c.price+i*23).toFixed(2)}</strong><div class="sku">${12-i*3} in stock</div></div><button class="add-cart">ADD TO CART</button></div></article>`).join('')}</section></div>`;$('.back-home').onclick=showHome;$$('.add-cart').forEach(b=>b.onclick=()=>{$('#cartCount').textContent=+$('#cartCount').textContent+1;b.textContent='ADDED ✓'}) ;scrollTo(0,0)}
function showHome(){$('#inventoryView').classList.add('hidden');$('#explorerView').classList.remove('hidden');scrollTo(0,0)}$$('[data-home]').forEach(b=>b.onclick=showHome);
renderCategories();renderDetail();updateVehicle();$('#partOverlay').innerHTML='';
